// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANvB-ir51zwANLtlE9dZF_-6MsAbsFxkE',
    appId: '1:758403667131:web:ecccaae51c83159228059e',
    messagingSenderId: '758403667131',
    projectId: 'app-did-e198a',
    authDomain: 'app-did-e198a.firebaseapp.com',
    storageBucket: 'app-did-e198a.firebasestorage.app',
    measurementId: 'G-CC8PQG8R5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFP11WDl8QxDMI50bWqb--iqyXkWybGR0',
    appId: '1:758403667131:android:40b88d65d07811f828059e',
    messagingSenderId: '758403667131',
    projectId: 'app-did-e198a',
    storageBucket: 'app-did-e198a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYGpML5UJtI3x4eVcneCUqA5xUd0KbG0',
    appId: '1:758403667131:ios:6d3b59d63974fa6a28059e',
    messagingSenderId: '758403667131',
    projectId: 'app-did-e198a',
    storageBucket: 'app-did-e198a.firebasestorage.app',
    androidClientId: '758403667131-dlpdfonmkug9vfl6g0kii92fje068leh.apps.googleusercontent.com',
    iosClientId: '758403667131-eebq1u2dkj96qt73htf4tqias392sdr3.apps.googleusercontent.com',
    iosBundleId: 'com.chandu.appdid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYYGpML5UJtI3x4eVcneCUqA5xUd0KbG0',
    appId: '1:758403667131:ios:6d3b59d63974fa6a28059e',
    messagingSenderId: '758403667131',
    projectId: 'app-did-e198a',
    storageBucket: 'app-did-e198a.firebasestorage.app',
    androidClientId: '758403667131-dlpdfonmkug9vfl6g0kii92fje068leh.apps.googleusercontent.com',
    iosClientId: '758403667131-eebq1u2dkj96qt73htf4tqias392sdr3.apps.googleusercontent.com',
    iosBundleId: 'com.chandu.appdid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANvB-ir51zwANLtlE9dZF_-6MsAbsFxkE',
    appId: '1:758403667131:web:f4f753a937464de428059e',
    messagingSenderId: '758403667131',
    projectId: 'app-did-e198a',
    authDomain: 'app-did-e198a.firebaseapp.com',
    storageBucket: 'app-did-e198a.firebasestorage.app',
    measurementId: 'G-L1F1H3SDLR',
  );
}
